export const ECHARTS_MODULE_OPTIONS = Symbol('ECHARTS_MODULE_OPTIONS');
export const ECHARTS_BROWSER_MANAGER = Symbol('ECHARTS_BROWSER_MANAGER');

export const ECHARTS_DEFAULT_WIDTH = 800;
export const ECHARTS_DEFAULT_HEIGHT = 600;
export const ECHARTS_DEFAULT_DEVICE_SCALE_FACTOR = 1;
export const ECHARTS_DEFAULT_BACKGROUND_COLOR = '#ffffff';
export const ECHARTS_DEFAULT_MAX_CONCURRENCY = 5;
export const ECHARTS_DEFAULT_PAGE_POOL_SIZE = 3;
export const ECHARTS_DEFAULT_TIMEOUT_MS = 30_000;
export const ECHARTS_DEFAULT_RENDER_TIMEOUT_MS = 10_000;
